# Generated by Django 2.2.6 on 2020-08-27 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecashflowam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=100)),
                ('amount', models.CharField(blank=True, default='NA', max_length=100)),
                ('forecast_amount', models.CharField(blank=True, default='NA', max_length=100)),
                ('forecast_percent', models.CharField(blank=True, default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
