# Generated by Django 2.2.6 on 2020-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecashflowam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecashflowam',
            old_name='amount',
            new_name='am_application_status',
        ),
        migrations.RenameField(
            model_name='ecashflowam',
            old_name='forecast_amount',
            new_name='am_date_fitcd',
        ),
        migrations.RenameField(
            model_name='ecashflowam',
            old_name='forecast_percent',
            new_name='am_district',
        ),
        migrations.RenameField(
            model_name='ecashflowam',
            old_name='name',
            new_name='am_id',
        ),
        migrations.AddField(
            model_name='ecashflowam',
            name='am_ref_number',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='ecashflowam',
            name='am_state',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='ecashflowam',
            name='am_tariff',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='ecashflowam',
            name='district',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='ecashflowam',
            name='es_description',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='ecashflowam',
            name='re_type',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='ecashflowam',
            name='re_type_text',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='ecashflowam',
            name='state',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
