apiVersion: apps/v1
kind: Deployment
metadata:
  name: seda-rcs-api-celery-beat
  labels:
    deployment: seda-rcs-api-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: seda-rcs-api-celery-beat
  template:
    metadata:
      labels:
        pod: seda-rcs-api-celery-beat
    spec:
      containers:
        - name: seda-rcs-api-celery-beat
          image: username/seda-rcs-api
          # celery -A seda-rcs-api beat -l debug
          command: ['celery', '-A', 'core', 'beat', '-l', 'debug']
          envFrom:
            - secretRef:
                name: seda-rcs-api-secret