# Generated by Django 2.2.6 on 2020-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200726_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('US', 'User'), ('AD', 'Admin')], default='US', max_length=2),
        ),
    ]
