# Generated by Django 2.2.6 on 2020-07-26 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, default='NA', max_length=100)),
                ('user_id', models.CharField(blank=True, default='NA', max_length=100)),
                ('project_id', models.CharField(blank=True, default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
