# Generated by Django 2.2.6 on 2020-07-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='phase',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
