# Generated by Django 2.2.6 on 2020-07-26 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NA', max_length=100)),
                ('activity_desc', models.CharField(blank=True, default='NA', max_length=100)),
                ('location', models.CharField(blank=True, default='NA', max_length=100)),
                ('activity_level', models.CharField(blank=True, default='NA', max_length=100)),
                ('start_date', models.DateTimeField(blank=True)),
                ('expected_completion_date', models.CharField(blank=True, default='NA', max_length=100)),
                ('project_timeframe', models.CharField(blank=True, default='NA', max_length=100)),
                ('activity_cost', models.CharField(blank=True, default='NA', max_length=100)),
                ('progress_level', models.CharField(blank=True, default='NA', max_length=100)),
                ('pic', models.CharField(blank=True, default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
