# Generated by Django 2.2.6 on 2020-07-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200726_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='project_id',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
