# Generated by Django 2.2.6 on 2020-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20200827_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='amount',
            new_name='ay_daa',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='forecast_amount',
            new_name='ay_export',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='forecast_percent',
            new_name='ay_generate',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='name',
            new_name='ay_id',
        ),
        migrations.AddField(
            model_name='income',
            name='ay_id_app',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='ay_prorate',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='ay_total_days',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='ay_year',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='ay_year_number',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='inf_cre_dt',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='inf_cre_usr',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='inf_mod_dt',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='inf_mod_usr',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
