# Generated by Django 2.2.6 on 2020-07-26 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('start_date', models.CharField(default='NA', max_length=100)),
                ('expected_completion_date', models.CharField(default='NA', max_length=100)),
                ('project_timeframe', models.CharField(default='NA', max_length=100)),
                ('department', models.CharField(default='NA', max_length=100)),
                ('owner_project', models.CharField(default='NA', max_length=100)),
                ('source_of_fund', models.CharField(default='NA', max_length=100)),
                ('project_cost', models.CharField(default='NA', max_length=100)),
                ('pic', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
