# Generated by Django 2.2.6 on 2020-07-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
