# Generated by Django 2.2.6 on 2020-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200726_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expected_completion_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
